apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
  namespace: jorder
data:
  JOrder__Authentication__JwtSigning__Issuer: "http://identity.jorder.localhost"
  JOrder__Authentication__JwtSigning__Audience: "jorder-api"
  ASPNETCORE_ENVIRONMENT: "Development"

