apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
  namespace: jorder
type: Opaque
stringData:
  ConnectionStrings__Identity: "Host=postgres;Port=5432;Database=jorder_identity;Username=postgres;Password=mypassword"

